import { ProjectDocument } from './types'

export const createSampleProject = (): ProjectDocument => ({
  schemaVersion: 'bimlite.v1',
  id: `project-${Date.now()}`,
  name: 'Raised Addition Concept',
  updatedAt: new Date().toISOString(),
  jurisdiction: {
    profile: 'GENERIC_IRC',
    edition: '2021/2024-ready',
    notes: 'Generic prescriptive residential profile. Local AHJ and licensed professional review still required.',
  },
  site: {
    units: 'imperial',
    boundary: [
      { x: -12, y: -12 },
      { x: 44, y: -12 },
      { x: 44, y: 34 },
      { x: -12, y: 34 },
    ],
    terrain: {
      type: 'slopedPlane',
      baseElevation: 0,
      plane: { origin: { x: 0, y: 0 }, slopeX: 0.025, slopeY: -0.015 },
      points: [
        { id: 'tp-1', x: -12, y: -12, z: -0.12 },
        { id: 'tp-2', x: 44, y: -12, z: 1.28 },
        { id: 'tp-3', x: 44, y: 34, z: 0.59 },
        { id: 'tp-4', x: -12, y: 34, z: -0.81 },
      ],
      contours: [],
    },
  },
  levels: [{ id: 'level-main', name: 'Main Floor', elevation: 3, height: 9 }],
  spaces: [
    {
      id: 'space-studio',
      name: 'Studio Addition',
      levelId: 'level-main',
      use: 'living',
      polygon: [
        { x: 0, y: 0 },
        { x: 28, y: 0 },
        { x: 28, y: 20 },
        { x: 0, y: 20 },
      ],
    },
  ],
  assemblies: {
    'wall-ext-2x6': {
      id: 'wall-ext-2x6',
      name: 'Exterior 2x6 Fiber Cement Wall',
      kind: 'wall',
      layers: [
        { role: 'finish', materialId: 'drywall-1-2', thickness: 0.5 },
        { role: 'structure', materialId: 'stud-2x6', spacing: 16 },
        { role: 'insulation', materialId: 'batt-r21', rValue: 21 },
        { role: 'sheathing', materialId: 'osb-7-16', thickness: 0.4375 },
        { role: 'weatherBarrier', materialId: 'house-wrap' },
        { role: 'siding', materialId: 'fiber-cement-siding', thickness: 0.3125 },
      ],
    },
    'floor-2x10': {
      id: 'floor-2x10',
      name: 'Raised 2x10 Floor Assembly With Oak Finish',
      kind: 'floor',
      layers: [
        { role: 'flooring', materialId: 'oak-flooring-3-4', thickness: 0.75 },
        { role: 'underlayment', materialId: 'floor-underlayment', thickness: 0.125 },
        { role: 'subfloor', materialId: 'subfloor-3-4', thickness: 0.75 },
        { role: 'structure', materialId: 'joist-2x10', spacing: 16 },
        { role: 'insulation', materialId: 'batt-r30', rValue: 30 },
      ],
    },
    'roof-asphalt-gable': {
      id: 'roof-asphalt-gable',
      name: 'Asphalt Shingle Gable Roof',
      kind: 'roof',
      layers: [
        { role: 'roofing', materialId: 'asphalt-shingle', thickness: 0.25 },
        { role: 'sheathing', materialId: 'osb-7-16', thickness: 0.4375 },
        { role: 'structure', materialId: 'rafter-2x8', spacing: 24 },
      ],
    },
    'wall-int-2x4': {
      id: 'wall-int-2x4',
      name: 'Interior 2x4 Drywall Partition',
      kind: 'wall',
      layers: [
        { role: 'finish', materialId: 'drywall-1-2', thickness: 0.5 },
        { role: 'structure', materialId: 'stud-2x4', spacing: 16 },
        { role: 'service', materialId: 'romex-12-2' },
        { role: 'finish', materialId: 'drywall-1-2', thickness: 0.5 },
      ],
    },
  },
  materials: {
    'stud-2x4': { id: 'stud-2x4', name: '2x4 SPF stud', category: 'lumber', unit: 'linearFt', wasteFactor: 0.1, nominal: '2x4', profile: { nominal: '2x4', actualWidth: 0.125, actualDepth: 0.2917, visualRole: 'dimensionalLumber' } },
    'stud-2x6': { id: 'stud-2x6', name: '2x6 SPF stud', category: 'lumber', unit: 'linearFt', wasteFactor: 0.1, nominal: '2x6', profile: { nominal: '2x6', actualWidth: 0.125, actualDepth: 0.4583, visualRole: 'dimensionalLumber' } },
    'joist-2x8': { id: 'joist-2x8', name: '2x8 floor joist', category: 'lumber', unit: 'linearFt', wasteFactor: 0.12, nominal: '2x8', profile: { nominal: '2x8', actualWidth: 0.125, actualDepth: 0.6042, visualRole: 'dimensionalLumber' } },
    'joist-2x10': { id: 'joist-2x10', name: '2x10 floor joist', category: 'lumber', unit: 'linearFt', wasteFactor: 0.12, nominal: '2x10', profile: { nominal: '2x10', actualWidth: 0.125, actualDepth: 0.7708, visualRole: 'dimensionalLumber' } },
    'stringer-2x12': { id: 'stringer-2x12', name: '2x12 stair stringer', category: 'lumber', unit: 'linearFt', wasteFactor: 0.16, nominal: '2x12', profile: { nominal: '2x12', actualWidth: 0.125, actualDepth: 0.9375, visualRole: 'dimensionalLumber' } },
    'rafter-2x8': { id: 'rafter-2x8', name: '2x8 rafter', category: 'lumber', unit: 'linearFt', wasteFactor: 0.12, nominal: '2x8', profile: { nominal: '2x8', actualWidth: 0.125, actualDepth: 0.6042, visualRole: 'dimensionalLumber' } },
    'beam-4x10': { id: 'beam-4x10', name: '4x10 built-up beam', category: 'lumber', unit: 'linearFt', wasteFactor: 0.08, nominal: '4x10', profile: { nominal: '4x10', actualWidth: 0.2917, actualDepth: 0.7708, visualRole: 'dimensionalLumber' } },
    'post-4x4-pt': { id: 'post-4x4-pt', name: '4x4 pressure treated post', category: 'lumber', unit: 'linearFt', wasteFactor: 0.12, nominal: '4x4', profile: { nominal: '4x4', actualWidth: 0.2917, actualDepth: 0.2917, visualRole: 'post' } },
    'post-4x6-pt': { id: 'post-4x6-pt', name: '4x6 pressure treated post', category: 'lumber', unit: 'linearFt', wasteFactor: 0.12, nominal: '4x6', profile: { nominal: '4x6', actualWidth: 0.2917, actualDepth: 0.4583, visualRole: 'post' } },
    'rim-2x10': { id: 'rim-2x10', name: '2x10 rim joist', category: 'lumber', unit: 'linearFt', wasteFactor: 0.08, nominal: '2x10', profile: { nominal: '2x10', actualWidth: 0.125, actualDepth: 0.7708, visualRole: 'dimensionalLumber' } },
    'subfloor-3-4': { id: 'subfloor-3-4', name: '3/4 in tongue-and-groove subfloor', category: 'sheetGood', unit: 'sqFt', wasteFactor: 0.1 },
    'floor-underlayment': { id: 'floor-underlayment', name: 'Floor underlayment', category: 'finish', unit: 'sqFt', wasteFactor: 0.08 },
    'oak-flooring-3-4': { id: 'oak-flooring-3-4', name: '3/4 in oak flooring', category: 'finish', unit: 'sqFt', wasteFactor: 0.12 },
    'osb-7-16': { id: 'osb-7-16', name: '7/16 in OSB sheathing', category: 'sheetGood', unit: 'sqFt', wasteFactor: 0.12 },
    'house-wrap': { id: 'house-wrap', name: 'Weather barrier house wrap', category: 'finish', unit: 'sqFt', wasteFactor: 0.1 },
    'drywall-1-2': { id: 'drywall-1-2', name: '1/2 in drywall', category: 'finish', unit: 'sqFt', wasteFactor: 0.12 },
    'fiber-cement-siding': { id: 'fiber-cement-siding', name: 'Fiber cement lap siding', category: 'finish', unit: 'sqFt', wasteFactor: 0.15 },
    'asphalt-shingle': { id: 'asphalt-shingle', name: 'Architectural asphalt shingles', category: 'roofing', unit: 'sqFt', wasteFactor: 0.12 },
    'batt-r21': { id: 'batt-r21', name: 'R-21 wall batt insulation', category: 'insulation', unit: 'sqFt', wasteFactor: 0.1 },
    'batt-r30': { id: 'batt-r30', name: 'R-30 floor/ceiling batt insulation', category: 'insulation', unit: 'sqFt', wasteFactor: 0.1 },
    'concrete-pier-block': { id: 'concrete-pier-block', name: 'Concrete pier block', category: 'concrete', unit: 'each', wasteFactor: 0.05 },
    'post-6x6-pt': { id: 'post-6x6-pt', name: '6x6 pressure treated post', category: 'lumber', unit: 'linearFt', wasteFactor: 0.12, nominal: '6x6', profile: { nominal: '6x6', actualWidth: 0.4583, actualDepth: 0.4583, visualRole: 'post' } },
    'romex-12-2': { id: 'romex-12-2', name: '12/2 NM-B cable', category: 'electrical', unit: 'linearFt', wasteFactor: 0.15 },
    'pex-1-2': { id: 'pex-1-2', name: '1/2 in PEX tubing', category: 'plumbing', unit: 'linearFt', wasteFactor: 0.15 },
  },
  elements: [
    {
      id: 'floor-1',
      type: 'floor',
      name: 'Raised floor platform',
      levelId: 'level-main',
      polygon: [
        { x: 0, y: 0 },
        { x: 28, y: 0 },
        { x: 28, y: 20 },
        { x: 0, y: 20 },
      ],
      elevation: 3,
      assemblyId: 'floor-2x10',
      joistDirection: 'x',
      joistSize: '2x10',
      joistSpacing: 16,
      beamSpacing: 10,
      pierSpacing: 7,
    },
    { id: 'wall-n', type: 'wall', name: 'North exterior wall', levelId: 'level-main', path: [{ x: 0, y: 0 }, { x: 28, y: 0 }], height: 9, assemblyId: 'wall-ext-2x6', bearing: true, exterior: true, studSize: '2x6', studSpacing: 16, joinPriority: 'miter' },
    { id: 'wall-e', type: 'wall', name: 'East exterior wall', levelId: 'level-main', path: [{ x: 28, y: 0 }, { x: 28, y: 20 }], height: 9, assemblyId: 'wall-ext-2x6', bearing: true, exterior: true, studSize: '2x6', studSpacing: 16, joinPriority: 'miter' },
    { id: 'wall-s', type: 'wall', name: 'South exterior wall', levelId: 'level-main', path: [{ x: 28, y: 20 }, { x: 0, y: 20 }], height: 9, assemblyId: 'wall-ext-2x6', bearing: true, exterior: true, studSize: '2x6', studSpacing: 16, joinPriority: 'miter' },
    { id: 'wall-w', type: 'wall', name: 'West exterior wall', levelId: 'level-main', path: [{ x: 0, y: 20 }, { x: 0, y: 0 }], height: 9, assemblyId: 'wall-ext-2x6', bearing: true, exterior: true, studSize: '2x6', studSpacing: 16, joinPriority: 'miter' },
    { id: 'door-1', type: 'opening', name: 'Entry door', levelId: 'level-main', hostWallId: 'wall-s', openingKind: 'door', center: 14, width: 3, height: 6.8, sillHeight: 0, headerSize: '2x10' },
    { id: 'window-1', type: 'opening', name: 'North window', levelId: 'level-main', hostWallId: 'wall-n', openingKind: 'window', center: 9, width: 4, height: 4, sillHeight: 3, headerSize: '2x10' },
    { id: 'window-2', type: 'opening', name: 'East window', levelId: 'level-main', hostWallId: 'wall-e', openingKind: 'window', center: 10, width: 3, height: 4, sillHeight: 3, headerSize: '2x8' },
    {
      id: 'roof-1',
      type: 'roof',
      name: 'Gable roof',
      levelId: 'level-main',
      footprint: [
        { x: 0, y: 0 },
        { x: 28, y: 0 },
        { x: 28, y: 20 },
        { x: 0, y: 20 },
      ],
      baseElevation: 12,
      roofType: 'gable',
      pitchRise: 6,
      pitchRun: 12,
      overhang: 1,
      rafterSize: '2x8',
      rafterSpacing: 24,
      assemblyId: 'roof-asphalt-gable',
    },
    { id: 'panel-1', type: 'electricalDevice', name: 'Main panel', levelId: 'level-main', deviceKind: 'panel', position: { x: 1, y: 1, z: 4 }, loadWatts: 0 },
    { id: 'circuit-1', type: 'circuit', name: 'Living receptacles', panelId: 'panel-1', amperage: 20, voltage: 120, breakerType: 'dualFunction', wireGauge: 12, deviceIds: ['outlet-1', 'outlet-2'] },
    { id: 'outlet-1', type: 'electricalDevice', name: 'North receptacle', levelId: 'level-main', deviceKind: 'outlet', position: { x: 7, y: 0.25, z: 1.5 }, circuitId: 'circuit-1', loadWatts: 180 },
    { id: 'outlet-2', type: 'electricalDevice', name: 'East GFCI receptacle', levelId: 'level-main', deviceKind: 'gfciOutlet', position: { x: 27.75, y: 8, z: 1.5 }, circuitId: 'circuit-1', loadWatts: 180 },
    { id: 'sink-1', type: 'plumbingFixture', name: 'Utility sink', levelId: 'level-main', fixtureKind: 'sink', position: { x: 24, y: 17, z: 3 }, supplyCount: 2, drainDiameter: 1.5, dfu: 2 },
    { id: 'drain-1', type: 'pipe', name: 'Sink drain', levelId: 'level-main', pipeKind: 'drain', materialId: 'pex-1-2', diameter: 1.5, slope: 0.25, path: [{ x: 24, y: 17, z: 2.2 }, { x: 16, y: 17, z: 2.03 }, { x: 16, y: 22, z: 1.92 }] },
  ],
  suppliers: {
    preferredSupplier: 'homeDepot',
    zipCode: '96813',
    products: [],
  },
})
